permissions
conda-forge/langchain-feedstock pull request #151
Opened 2023-12-19 20:46 UTC by efriis

2023-12-19 20:47 UTC, pavelzw requested changes
This is a community lead project. Feedstocks are maintained by the conda-forge community and not exclusively by the package maintainers.

2023-12-19 20:49 UTC, closed without merging

2023-12-19 20:50 UTC, pavelzw commented
Please take a look at the PR template! This screws up the whole conda-forge build system.

> Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

2023-12-19 20:51 UTC, efriis commented
Hey @pavelzw ! Could you respond to my email? Also happy to chat here if better :)

Thanks for the note about the personal fork - hopefully deleting the branch resolved it.

2023-12-19 20:58 UTC, pavelzw commented
I'll answer here instead of to the email.

As just explained in https://github.com/conda-forge/langchain-feedstock/pull/151#pullrequestreview-1789692457, conda-forge is a community-lead project. Usually, packages are maintained by the conda-forge community and not exclusively by the original package creators.

You are now in the @conda-forge/langchain team and have the necessary permissions to maintain this package. It is not common for people to kick out other maintainers, even though they may not be officially affiliated with the original package.

I wanted to add myself as a maintainer of langchain-core in https://github.com/conda-forge/langchain-core-feedstock/pull/5 because I wanted to help out bring older versions of langchain-core (especially 0.0.10 for @jasonwell) (see https://github.com/conda-forge/langchain-feedstock/pull/143#issuecomment-1861277383 and https://github.com/conda-forge/langchain-feedstock/pull/142#issuecomment-1858246860).

In general, it can be beneficial to also have somebody who is somewhat knowledgeable as a package maintainer. I don't see a reason why you would need exclusive maintainer rights.

2023-12-19 21:17 UTC, pavelzw commented on README.md
> +* [@langchain-ai](https://github.com/langchain-ai/)
Don't change the readme since it's autogenerated

2023-12-20 19:32 UTC, efriis commented
Thanks for clarifying! I'm new to the conda world.

Added langchain-core 0.0.10 yesterday, and can bump lower if previous versions are needed.